name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build tools
      run: pip install build twine

    - name: Build package
      run: python -m build

    # IMPORTANT: Currently configured to publish to PyPI.
    # https://upload.pypi.org/legacy/
    # https://test.pypi.org/legacy/
    
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/