# .streamlit/config.toml

[server]
# Disable rerunning the script when source files change. You'll need to manually rerun.
runOnSave = false

# Explicitly disable the file watching mechanism that seems to cause the conflict.
# Options: 'auto', 'poll', 'watchdog', 'none'. 'none' is the most robust for disabling.
fileWatcherType = "none"

# Optional: Reduce server overhead slightly
# [global]
# disableWatchdogWarning = true # If fileWatcherType = 'watchdog' and it gives warnings

# Optional: Might clear some browser state on reconnection? Unlikely related to backend crash.
# [client]
# clearCacheOnPageLoad = true